1.netkeiba.comからのスクレイピング(NHKマイルカップ)

In [6]:
import pandas as pd
url='https://db.netkeiba.com/race/201805020611/'
pd.read_html(url)[0]

,着順,枠番,馬番,馬名,性齢,斤量,騎手,タイム,着差,単勝,人気,馬体重,調教師
0,1,6,11,ケイアイノーテック,牡3,57,藤岡佑介,1:32.8,NaN,12.8,6,456(0),[西] 平田修
1,2,5,9,ギベオン,牡3,57,Ｍ．デム,1:32.8,クビ,5.2,2,508(+6),[西] 藤原英昭
2,3,8,17,レッドヴェイロン,牡3,57,岩田康誠,1:32.8,アタマ,25.0,9,474(+4),[西] 石坂正
3,4,8,16,ミスターメロディ,牡3,57,福永祐一,1:33.0,3/4,14.7,7,486(+4),[西] 藤原英昭
4,5,3,5,プリモシーン,牝3,55,戸崎圭太,1:33.0,クビ,10.8,5,478(0),[東] 木村哲也
5,6,5,10,パクスアメリカーナ,牡3,57,川田将雅,1:33.2,1.1/4,9.6,4,464(+2),[西] 中内田充
6,7,4,8,ダノンスマッシュ,牡3,57,北村友一,1:33.2,クビ,75.0,13,470(+4),[西] 安田隆行
7,8,1,1,カツジ,牡3,57,松山弘平,1:33.5,1.3/4,15.6,8,484(+6),[西] 池添兼雄
8,9,7,14,デルタバローズ,牡3,57,石橋脩,1:33.5,ハナ,113.2,16,488(-14),[東] 堀宣行
9,10,7,15,カシアス,牡3,57,浜中俊,1:33.5,クビ,137.1,17,480(+2),[西] 清水久詞
10,11,3,6,リョーノテソーロ,牡3,57,吉田隼人,1:33.7,1.1/4,112.1,15,508(-6),[東] 武井亮
11,12,4,7,タワーオブロンドン,牡3,57,ルメール,1:33.8,クビ,2.6,1,510(0),[東] 藤沢和雄
12,13,2,4,フロンティア,牡3,57,内田博幸,1:33.8,クビ,66.8,12,462(+6),[西] 中内田充
13,14,2,3,テトラドラクマ,牝3,55,田辺裕信,1:33.9,クビ,7.5,3,458(-4),[東] 小西一男
14,15,1,2,ファストアプローチ,牡3,57,蛯名正義,1:34.0,3/4,90.5,14,530(-14),[東] 藤沢和雄
15,16,7,13,ルーカス,牡3,57,ボウマン,1:34.5,3,42.3,10,500(+8),[東] 堀宣行
16,17,6,12,アンコールプリュ,牝3,55,藤岡康太,1:34.6,1/2,141.4,18,420(-2),[西] 友道康夫
17,18,8,18,ロックディスタウン,牝3,55,池添謙一,1:36.3,大,66.1,11,490(-8),[東] 藤沢和雄

過去15分のレースを取得

In [3]:
race_id_list=[]
for year in range(2006,2020,1):
    race_id = str(year)+'05020611'
    race_id_list.append(race_id)
race_id_list

['200605020611',
 '200705020611',
 '200805020611',
 '200905020611',
 '201005020611',
 '201105020611',
 '201205020611',
 '201305020611',
 '201405020611',
 '201505020611',
 '201605020611',
 '201705020611',
 '201805020611',
 '201905020611']

In [4]:
import time
def scrape_race_results(race_id_list):
    race_results={}
    for race_id in race_id_list:
        url='https://db.netkeiba.com/race/' + race_id
        race_results[race_id]=pd.read_html(url)[0]
        time.sleep(1)
    return race_results

In [5]:
test=scrape_race_results(race_id_list)

NameError: name 'pd' is not defined

In [5]:
for key in test.keys():
    test[key].index=[key]*len(test[key])

過去15年分のレースを１つのデータフレームにまとめる

In [6]:
results=pd.concat([test[key] for key in test.keys()],sort=False)

In [17]:
results[results['人気']==1]

,着順,枠番,馬番,馬名,性齢,斤量,騎手,タイム,着差,単勝,人気,馬体重,調教師
200605020611,6,8,18,フサイチリシャール,牡3,57,福永祐一,1:34.0,1.3/4,2.6,1,490(+4),[西] 松田国英
200705020611,2,5,10,ローレルゲレイロ,牡3,57,藤田伸二,1:34.4,1/2,5.5,1,460(-4),[西] 昆貢
200805020611,1,5,9,ディープスカイ,牡3,57,四位洋文,1:34.2,NaN,4.3,1,508(0),[西] 昆貢
200905020611,9,8,16,ブレイクランアウト,牡3,57,武豊,1:33.4,ハナ,3.3,1,442(0),[東] 戸田博文
201005020611,1,7,13,ダノンシャンティ,牡3,57,安藤勝己,1:31.4,NaN,2.6,1,468(+2),[西] 松田国英
201105020611,1,7,13,グランプリボス,牡3,57,ウィリア,1:32.2,NaN,4.6,1,500(-6),[西] 矢作芳人
201205020611,1,3,5,カレンブラックヒル,牡3,57,秋山真一,1:34.5,NaN,3.7,1,460(-6),[西] 平田修
201305020611,7,7,15,エーシントップ,牡3,57,内田博幸,1:33.1,クビ,2.9,1,528(+4),[西] 西園正都
201405020611,1,5,10,ミッキーアイル,牡3,57,浜中俊,1:33.2,NaN,1.9,1,478(+8),[西] 音無秀孝
201505020611,5,1,2,グランシルク,牡3,57,戸崎圭太,1:33.9,クビ,4.3,1,480(+2),[東] 戸田博文
201605020611,1,2,4,メジャーエンブレム,牝3,55,ルメール,1:32.8,NaN,2.3,1,496(-6),[東] 田村康仁
201705020611,17,2,4,カラクレナイ,牝3,55,Ｍ．デム,1:34.2,1.1/4,5.0,1,484(+4),[西] 松下武士
201805020611,12,4,7,タワーオブロンドン,牡3,57,ルメール,1:33.8,クビ,2.6,1,510(0),[東] 藤沢和雄
201905020611,5(降),4,7,グランアレグリア,牝3,55,ルメール,1:32.7,NaN,1.5,1,474(-2),[東] 藤沢和雄

In [8]:
results['着順'].value_counts()

6        12
1        11
10       11
17       11
16       11
15       11
14       11
13       11
12       11
11       11
9        11
8        11
5        11
4        11
3        11
2        11
18       11
7        10
3         3
10        3
11        3
13        3
8         3
7         3
6         3
16        3
9         3
1         3
15        3
12        3
4         3
2         3
14        3
5         2
17        2
失         1
中         1
18(降)     1
5(降)      1
18        1
Name: 着順, dtype: int64

In [9]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 252 entries, 200605020611 to 201905020611
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   着順      252 non-null    object
 1   枠番      252 non-null    int64
 2   馬番      252 non-null    int64
 3   馬名      252 non-null    object
 4   性齢      252 non-null    object
 5   斤量      252 non-null    int64
 6   騎手      252 non-null    object
 7   タイム     251 non-null    object
 8   着差      234 non-null    object
 9   単勝      252 non-null    float64
 10  人気      252 non-null    int64
 11  馬体重     252 non-null    object
 12  調教師     252 non-null    object
dtypes: float64(1), int64(4), object(8)
memory usage: 27.6+ KB

In [10]:
#着順のデータ型を一度str型に変える

In [11]:
results['着順']=results['着順'].astype(str)

In [100]:
results['着順'].value_counts()

6        15
8        14
14       14
15       14
16       14
11       14
4        14
13       14
12       14
2        14
9        14
3        14
1        14
10       14
7        13
17       13
5        13
18       12
5(降)      1
18(降)     1
中         1
失         1
Name: 着順, dtype: int64

2.データの前処理

In [12]:
def preprocessing(results):
    df=results.copy()
    #着順が数字以外の物を取り除く
    df=df[~(df['着順'].astype(str).str.contains('\D'))]
    df['着順']=df['着順'].astype(int)
    
    #性齢の性と年齢に分ける
    df['性']=df['性齢'].map(lambda x:str(x)[0])
    df['年齢']=df['性齢'].map(lambda x:str(x)[1:]).astype(int)
    
    #馬体重を体重と体重変化に分ける
    df['体重']=df['馬体重'].str.split('(',expand=True)[0].astype(int)
    df['体重変化']=df['馬体重'].str.split('(',expand=True)[1].str[:-1].astype(int)
    
    #データをint,floatに変換
    
    #不要な列の削除
    df.drop(['タイム','着差','調教師','性齢','馬体重'],axis=1,inplace=True)
    
    return df

In [13]:
results1=preprocessing(results)

In [15]:
results1[results1['人気']==1]

              着順  枠番  馬番         馬名  斤量    騎手   単勝  人気  性  年齢   体重  体重変化
200605020611   6   8  18  フサイチリシャール  57  福永祐一  2.6   1  牡   3  490     4
200705020611   2   5  10   ローレルゲレイロ  57  藤田伸二  5.5   1  牡   3  460    -4
200805020611   1   5   9    ディープスカイ  57  四位洋文  4.3   1  牡   3  508     0
200905020611   9   8  16  ブレイクランアウト  57    武豊  3.3   1  牡   3  442     0
201005020611   1   7  13   ダノンシャンティ  57  安藤勝己  2.6   1  牡   3  468     2
201105020611   1   7  13    グランプリボス  57  ウィリア  4.6   1  牡   3  500    -6
201205020611   1   3   5  カレンブラックヒル  57  秋山真一  3.7   1  牡   3  460    -6
201305020611   7   7  15    エーシントップ  57  内田博幸  2.9   1  牡   3  528     4
201405020611   1   5  10    ミッキーアイル  57   浜中俊  1.9   1  牡   3  478     8
201505020611   5   1   2     グランシルク  57  戸崎圭太  4.3   1  牡   3  480     2
201605020611   1   2   4  メジャーエンブレム  55  ルメール  2.3   1  牝   3  496    -6
201705020611  17   2   4     カラクレナイ  55  Ｍ．デム  5.0   1  牝   3  484     4
201805020611  12   4   7  タワーオブロンドン  57  ルメール  2.6   1  牡   3  510     0

In [18]:
results1.to_pickle('results1.pickle')

クラスHorseResults1

In [11]:
import pandas as pd
import datetime


def preprocessing(results):
    df=results.copy()
    #着順が数字以外の物を取り除く
    df['着順']=pd.to_numeric(df['着順'],errors='coerce')
    df=df.dropna(subset=['着順'])
    df['着順']=df['着順'].astype(int)
    
    #性齢の性と年齢に分ける
    df['性']=df['性齢'].map(lambda x:str(x)[0])
    df['年齢']=df['性齢'].map(lambda x:str(x)[1:]).astype(int)
    
    #馬体重を体重と体重変化に分ける
    df['体重']=df['馬体重'].str.split('(',expand=True)[0].astype(int)
    df['体重変化']=df['馬体重'].str.split('(',expand=True)[1].str[:-1].astype(int)
    
    #データをint,floatに変換
    df['単勝']=df['単勝'].astype(float)
    
    #不要な列の削除
    df.drop(['タイム','着差','調教師','性齢','馬体重'],axis=1,inplace=True)
    
    return df
    



class HorseResults1:
    
    def __init__(self,horse_results):
        self.horse_results=horse_results[['日付','着順','賞金']]
        self.preprocessing()
        
    #データの前処理
    def preprocessing(self):
        df=self.horse_results.copy()
        #着順が数字以外の物を取り除く
        #まず着順のデータを全て数値の型に変更し、その後欠損値を削除する
        df['着順']=pd.to_numeric(df['着順'],errors='coerce')
        df=df.dropna(subset=['着順'])
        #着順をint型に変更
        df['着順']=df['着順'].astype(int)
        
        #日付をdatetime型に変更
        df['date']=pd.to_datetime(df['日付'])
        df.drop(['日付'],axis=1,inplace=True)
        
        #あとで、賞金の平均を取りたいから欠損値を0に変更しておく
        df['賞金'].fillna(0,inplace=True)
        
        self.horse_results = df
    
    #馬ごとの過去のレースの着順と賞金の平均を取る
    def average(self,horse_id_list,date,n_samples='all'):   #初期値として、allとしその場合、過去の全てのレースの着順と賞金の平均をとった
        target_df=self.horse_results.loc[horse_id_list]
        if n_samples=='all':
            filtered_df=target_df[target_df['date'] < date]
        elif  n_samples > 0:
            target_df=self.horse_results.loc[horse_id_list]
            filtered_df=target_df[target_df['date'] < date].\
                sort_values('date',ascending=False).groupby(level=0).head(n_samples)
        
        average=filtered_df.groupby(level=0)[['着順','賞金']].mean()
    
        return average.rename(columns={'着順':'着順_{}R'.format(n_samples)})
    
    def merge(self,results,date,n_samples='all'):
        df=results[results['date']==date]
        horse_id_list=df['horse_id']
        merged_df=df.merge(self.average(horse_id_list,date,n_samples),left_on='horse_id',right_index=True,how='left')
        return merged_df
    
    def merge_all(self,results,n_samples='all'):
        date_list=results['date'].drop_duplicates().tolist()
        merged_df=pd.concat([self.merge(results, date,n_samples) for date in date_list ])
        return merged_df

In [17]:
import time
import requests
from bs4 import BeautifulSoup
import re

def scrape_race_results(race_id_list):
    race_results={}
    for race_id in race_id_list:
        url='https://db.netkeiba.com/race/'+race_id
        df=pd.read_html(url)[0]
        
        #horse_id,jockey_idのスクレイピング
        html=requests.get(url)
        html.encoding='EUC-JP'
        soup=BeautifulSoup(html.text,'html.parser')
        
        #horse_id
        horse_id_list=[]
        horse_a_list=\
          soup.find('table',attrs={'summary':'レース結果'}).find_all('a',attrs={'href':re.compile(r'^/horse')})
        for a in horse_a_list:
            horse_id=re.findall(r'\d+',a['href'])
            horse_id_list.append(horse_id[0])
            
        #jockey_id
        jockey_id_list=[]
        jockey_a_list=\
          soup.find('table',attrs={'summary':'レース結果'}).find_all('a',attrs={'href':re.compile(r'^/jockey')})
        for a in jockey_a_list:
            jockey_id=re.findall(r'\d+',a['href'])
            jockey_id_list.append(jockey_id[0])
         
        
        df['horse_id']=horse_id_list
        df['jockey_id']=jockey_id_list
        
        race_results[race_id]=df
        time.sleep(1)
    return race_results

In [28]:
test=scrape_race_results(race_id_list)

In [34]:
for key in test.keys():
    test[key].index=[key]*len(test[key])

In [35]:
results2=pd.concat([test[key] for key in test.keys()])

In [39]:
results2=preprocessing(results2)

In [40]:
results2.to_pickle('results2.pickle')

In [41]:
results2

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,horse_id,jockey_id,性,年齢,体重,体重変化
200605020611,1,3,6,ロジック,57,武豊,8.7,3,2003100454,00666,牡,3,488,0
200605020611,2,1,2,ファイングレイン,57,横山典弘,25.9,9,2003102667,00660,牡,3,476,-6
200605020611,3,7,15,キンシャサノキセキ,55,安藤勝己,14.8,6,2003110212,00945,牡,3,472,8
200605020611,4,2,4,アポロノサトリ,57,蛯名正義,15.9,7,2003110138,00663,牡,3,436,-6
200605020611,5,8,17,ドラゴンウェルズ,57,藤田伸二,43.2,11,2003110095,00705,牡,3,486,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,14,1,1,クリノガウディー,57,藤岡佑介,87.0,13,2016103690,01093,牡,3,488,0
201905020611,15,7,15,ヴィッテルスバッハ,57,戸崎圭太,19.9,5,2016104475,05386,牡,3,458,-4
201905020611,16,2,4,イベリス,55,浜中俊,77.9,11,2016101285,01115,牝,3,450,-2
201905020611,17,5,9,ミッキーブラック,57,岩田康誠,285.2,17,2016104626,05203,牡,3,474,4
201905020611,18,6,11,ロードグラディオ,57,大野拓弥,402.7,18,2016101154,01096,牡,3,470,-4

In [13]:
race_infos={}
def scrape_race_date(race_id_list):
    for race_id in race_id_list:
        url="https://db.netkeiba.com/race/" + race_id
        html=requests.get(url)
        html.encoding='EUC-JP'
        soup=BeautifulSoup(html.text,'html.parser')
    
        text=soup.find('div',attrs={'class':'data_intro'}).find_all('p')[1].text
        info=re.findall(r'\w+',text)[0]
        race_infos[race_id]=info
        time.sleep(1)
    return race_infos

In [18]:
race_infos=scrape_race_date(race_id_list)

In [52]:
race_infos

{'200605020611': '2006年5月7日',
 '200705020611': '2007年5月6日',
 '200805020611': '2008年5月11日',
 '200905020611': '2009年5月10日',
 '201005020611': '2010年5月9日',
 '201105020611': '2011年5月8日',
 '201205020611': '2012年5月6日',
 '201305020611': '2013年5月5日',
 '201405020611': '2014年5月11日',
 '201505020611': '2015年5月10日',
 '201605020611': '2016年5月8日',
 '201705020611': '2017年5月7日',
 '201805020611': '2018年5月6日',
 '201905020611': '2019年5月5日'}

In [19]:
date_list=race_infos.values()
index1=race_infos.keys()
column1=['date']
date_df=pd.DataFrame(date_list,index=index1,columns=column1)

In [20]:
date_df['date']=pd.to_datetime(date_df['date'],format='%Y年%m月%d日')

In [21]:
date_df

                   date
200605020611 2006-05-07
200705020611 2007-05-06
200805020611 2008-05-11
200905020611 2009-05-10
201005020611 2010-05-09
201105020611 2011-05-08
201205020611 2012-05-06
201305020611 2013-05-05
201405020611 2014-05-11
201505020611 2015-05-10
201605020611 2016-05-08
201705020611 2017-05-07
201805020611 2018-05-06
201905020611 2019-05-05

日付のデータをメインのデータ(results2)にマージする

In [22]:
results2=results2.merge(date_df,left_index=True,right_index=True,how='inner')

In [23]:
results2

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,horse_id,jockey_id,性,年齢,体重,体重変化,date
200605020611,1,3,6,ロジック,57,武豊,8.7,3,2003100454,00666,牡,3,488,0,2006-05-07
200605020611,2,1,2,ファイングレイン,57,横山典弘,25.9,9,2003102667,00660,牡,3,476,-6,2006-05-07
200605020611,3,7,15,キンシャサノキセキ,55,安藤勝己,14.8,6,2003110212,00945,牡,3,472,8,2006-05-07
200605020611,4,2,4,アポロノサトリ,57,蛯名正義,15.9,7,2003110138,00663,牡,3,436,-6,2006-05-07
200605020611,5,8,17,ドラゴンウェルズ,57,藤田伸二,43.2,11,2003110095,00705,牡,3,486,0,2006-05-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,14,1,1,クリノガウディー,57,藤岡佑介,87.0,13,2016103690,01093,牡,3,488,0,2019-05-05
201905020611,15,7,15,ヴィッテルスバッハ,57,戸崎圭太,19.9,5,2016104475,05386,牡,3,458,-4,2019-05-05
201905020611,16,2,4,イベリス,55,浜中俊,77.9,11,2016101285,01115,牝,3,450,-2,2019-05-05
201905020611,17,5,9,ミッキーブラック,57,岩田康誠,285.2,17,2016104626,05203,牡,3,474,4,2019-05-05
201905020611,18,6,11,ロードグラディオ,57,大野拓弥,402.7,18,2016101154,01096,牡,3,470,-4,2019-05-05

In [24]:
horse_id_list=results2['horse_id'].unique()

In [25]:
def scrape_horse_results(horse_id_list):
    horse_results={}
    for horse_id in horse_id_list:
        url='https://db.netkeiba.com/horse/'+horse_id
        df=pd.read_html(url)[3]
        if df.columns[0]=='受賞歴':
            df=pd.read_html(url)[4]
        horse_results[horse_id]=df
        time.sleep(1)
    return horse_results

In [26]:
horse_results=scrape_horse_results(horse_id_list)

In [27]:
for key in horse_results.keys():
    horse_results[key].index=[key]*len(horse_results[key])

In [28]:
horse_results=pd.concat([horse_results[key] for key in horse_results.keys()])

In [30]:
horse_results

,日付,開催,天気,R,レース名,映像,頭数,枠番,馬番,オッズ,...,着差,ﾀｲﾑ指数,通過,ペース,上り,馬体重,厩舎ｺﾒﾝﾄ,備考,勝ち馬(2着馬),賞金
2003100454,2009/08/23,3小倉4,晴,10.0,小倉日経OP(OP),NaN,16.0,3.0,5,25.7,...,1.2,**,9-9-10-12,35.1-35.7,36.0,514(+8),NaN,NaN,マストビートゥルー,NaN
2003100454,2009/07/12,3阪神8,晴,10.0,プロキオンS(G3),NaN,16.0,5.0,9,103.4,...,1.4,**,7-7,34.6-36.3,37.0,506(-6),NaN,NaN,ランザローテ,NaN
2003100454,2008/05/11,3京都6,晴,11.0,都大路S(OP),NaN,18.0,6.0,12,15.8,...,1.0,**,9-7,35.9-35.2,35.8,512(+2),NaN,NaN,フサイチアウステル,NaN
2003100454,2008/04/13,1福島2,曇,11.0,福島民報杯(OP),NaN,16.0,7.0,13,10.9,...,1.3,**,5-5-6-6,34.8-37.0,37.9,510(-2),NaN,NaN,フィールドベアー,NaN
2003100454,2008/03/15,1阪神5,晴,11.0,大阪城S(OP),NaN,16.0,1.0,2,15.3,...,0.5,**,9-9,34.9-35.3,35.2,512(+6),NaN,NaN,オースミグラスワン,360.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016101154,2019/04/13,2阪神7,晴,11.0,アーリントンC(G3),NaN,18.0,1.0,2,50.8,...,0.2,**,4-3,35.0-34.4,34.3,474(+4),NaN,NaN,イベリス,NaN
2016101154,2019/02/09,2京都5,曇,9.0,こぶし賞(500万下),NaN,8.0,7.0,7,13.2,...,0.0,**,2-1,36.3-34.9,34.9,470(-8),NaN,NaN,(マイネルウィルトス),1018.9
2016101154,2018/12/23,5阪神8,曇,9.0,千両賞(500万下),NaN,12.0,7.0,10,28.4,...,0.5,**,2-2,35.4-35.3,35.6,478(0),NaN,NaN,マイネルフラップ,100.0
2016101154,2018/11/24,5京都7,晴,3.0,2歳未勝利,NaN,11.0,5.0,6,2.7,...,-0.1,**,2-2,35.6-34.9,34.7,478(-4),NaN,NaN,(スギノヴォルケーノ),500.0
2016101154,2018/10/28,4京都9,晴,5.0,2歳新馬,NaN,15.0,1.0,1,5.8,...,0.3,**,5-3,35.5-35.6,35.5,482(0),NaN,NaN,メトロポール,280.0

In [31]:
hr=HorseResults1(horse_results)
test=hr.merge_all(results2,n_samples=3)

In [35]:
test

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,horse_id,jockey_id,性,年齢,体重,体重変化,date,着順_3R,賞金
200605020611,1,3,6,ロジック,57,武豊,8.7,3,2003100454,00666,牡,3,488,0,2006-05-07,2.666667,1344.966667
200605020611,2,1,2,ファイングレイン,57,横山典弘,25.9,9,2003102667,00660,牡,3,476,-6,2006-05-07,6.333333,742.133333
200605020611,3,7,15,キンシャサノキセキ,55,安藤勝己,14.8,6,2003110212,00945,牡,3,472,8,2006-05-07,3.666667,740.733333
200605020611,4,2,4,アポロノサトリ,57,蛯名正義,15.9,7,2003110138,00663,牡,3,436,-6,2006-05-07,6.333333,270.000000
200605020611,5,8,17,ドラゴンウェルズ,57,藤田伸二,43.2,11,2003110095,00705,牡,3,486,0,2006-05-07,3.666667,435.766667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,14,1,1,クリノガウディー,57,藤岡佑介,87.0,13,2016103690,01093,牡,3,488,0,2019-05-05,8.000000,943.466667
201905020611,15,7,15,ヴィッテルスバッハ,57,戸崎圭太,19.9,5,2016104475,05386,牡,3,458,-4,2019-05-05,3.000000,735.733333
201905020611,16,2,4,イベリス,55,浜中俊,77.9,11,2016101285,01115,牝,3,450,-2,2019-05-05,2.000000,1890.566667
201905020611,17,5,9,ミッキーブラック,57,岩田康誠,285.2,17,2016104626,05203,牡,3,474,4,2019-05-05,8.666667,0.000000
201905020611,18,6,11,ロードグラディオ,57,大野拓弥,402.7,18,2016101154,01096,牡,3,470,-4,2019-05-05,4.333333,372.966667

In [36]:
results3=test.drop(['horse_id','騎手','馬名','date'],axis=1)

In [44]:
results3

,枠番,馬番,斤量,単勝,人気,jockey_id,性,年齢,体重,体重変化,着順_3R,賞金,rank
200605020611,3,6,57,8.7,3,666,牡,3,488,0,2.666667,1344.966667,1
200605020611,1,2,57,25.9,9,660,牡,3,476,-6,6.333333,742.133333,1
200605020611,7,15,55,14.8,6,945,牡,3,472,8,3.666667,740.733333,1
200605020611,2,4,57,15.9,7,663,牡,3,436,-6,6.333333,270.000000,0
200605020611,8,17,57,43.2,11,705,牡,3,486,0,3.666667,435.766667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,1,1,57,87.0,13,1093,牡,3,488,0,8.000000,943.466667,0
201905020611,7,15,57,19.9,5,5386,牡,3,458,-4,3.000000,735.733333,0
201905020611,2,4,55,77.9,11,1115,牝,3,450,-2,2.000000,1890.566667,0
201905020611,5,9,57,285.2,17,5203,牡,3,474,4,8.666667,0.000000,0
201905020611,6,11,57,402.7,18,1096,牡,3,470,-4,4.333333,372.966667,0

In [38]:
results3['rank']=results3['着順'].map(lambda x:1 if x < 4 else 0)

In [40]:
results3['jockey_id']=results3['jockey_id'].astype(int)

In [171]:
results3['jockey_id']=results3['jockey_id'].astype(int)

In [42]:
results3.drop(['着順'],axis=1,inplace=True)

In [45]:
X=results3.drop(['rank'],axis=1)

In [43]:
y=results3['rank']

In [46]:
X=pd.get_dummies(X)

In [47]:
X

,枠番,馬番,斤量,単勝,人気,jockey_id,年齢,体重,体重変化,着順_3R,賞金,性_牝,性_牡
200605020611,3,6,57,8.7,3,666,3,488,0,2.666667,1344.966667,0,1
200605020611,1,2,57,25.9,9,660,3,476,-6,6.333333,742.133333,0,1
200605020611,7,15,55,14.8,6,945,3,472,8,3.666667,740.733333,0,1
200605020611,2,4,57,15.9,7,663,3,436,-6,6.333333,270.000000,0,1
200605020611,8,17,57,43.2,11,705,3,486,0,3.666667,435.766667,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,1,1,57,87.0,13,1093,3,488,0,8.000000,943.466667,0,1
201905020611,7,15,57,19.9,5,5386,3,458,-4,3.000000,735.733333,0,1
201905020611,2,4,55,77.9,11,1115,3,450,-2,2.000000,1890.566667,1,0
201905020611,5,9,57,285.2,17,5203,3,474,4,8.666667,0.000000,0,1
201905020611,6,11,57,402.7,18,1096,3,470,-4,4.333333,372.966667,0,1

In [197]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,shuffle=False)

In [187]:
y

200605020611    1
200605020611    1
200605020611    1
200605020611    0
200605020611    0
               ..
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
Name: rank, Length: 248, dtype: int64

In [121]:
train['着順']

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,horse_id,jockey_id,性,年齢,体重,体重変化,着順_3R,賞金,rank
200605020611,1,3,6,ロジック,57,武豊,8.7,3,2003100454,00666,牡,3,488,0,2.666667,1344.966667,1
200605020611,2,1,2,ファイングレイン,57,横山典弘,25.9,9,2003102667,00660,牡,3,476,-6,6.333333,742.133333,1
200605020611,3,7,15,キンシャサノキセキ,55,安藤勝己,14.8,6,2003110212,00945,牡,3,472,8,3.666667,740.733333,1
200605020611,4,2,4,アポロノサトリ,57,蛯名正義,15.9,7,2003110138,00663,牡,3,436,-6,6.333333,270.000000,0
200605020611,5,8,17,ドラゴンウェルズ,57,藤田伸二,43.2,11,2003110095,00705,牡,3,486,0,3.666667,435.766667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201505020611,14,2,3,クールホタルビ,55,吉田豊,156.2,18,2012103383,00733,牝,3,440,6,15.000000,0.000000,0
201505020611,15,4,8,ナイトフォックス,57,田中勝春,142.6,17,2012104122,00684,牡,3,472,6,7.333333,260.000000,0
201505020611,16,3,6,レンイングランド,57,内田博幸,102.8,14,2012101011,00422,牡,3,508,0,9.666667,123.333333,0
201505020611,17,8,18,マテンロウハピネス,57,浜中俊,35.6,12,2012102308,01115,牡,3,444,2,4.666667,945.400000,0
201505020611,18,3,5,タガノアザガル,57,松田大作,106.9,15,2012100528,01030,牡,3,432,-8,6.666667,1255.733333,0

In [106]:
train['rank']=train['着順'].map(lambda x: 1 if x<4 else 0)
test['rank']=test['着順'].map(lambda x: 1 if x<4 else 0)
X_train=train.drop(['着順','rank'],axis=1)
y_train=train['rank']
X_test=test.drop(['着順','rank'],axis=1)
y_test=test['rank']

/Users/higuchidaisuke/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/higuchidaisuke/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [111]:
X_train=X_train.drop(['馬名','騎手','horse_id'],axis=1)
X_train['jockey_id']=X_train['jockey_id'].astype(int)

In [112]:
X_test=X_test.drop(['馬名','騎手','horse_id'],axis=1)
X_test['jockey_id']=X_test['jockey_id'].astype(int)

In [198]:
X_train=pd.get_dummies(X_train)
X_test=pd.get_dummies(X_test)

In [200]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223 entries, 200605020611 to 201805020611
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   枠番         223 non-null    int64
 1   馬番         223 non-null    int64
 2   斤量         223 non-null    int64
 3   単勝         223 non-null    float64
 4   人気         223 non-null    int64
 5   jockey_id  223 non-null    int64
 6   年齢         223 non-null    int64
 7   体重         223 non-null    int64
 8   体重変化       223 non-null    int64
 9   着順_3R      223 non-null    float64
 10  賞金         223 non-null    float64
 11  性_牝        223 non-null    uint8
 12  性_牡        223 non-null    uint8
dtypes: float64(3), int64(8), uint8(2)
memory usage: 21.3+ KB

In [120]:
y_test.value_counts()

0    59
1    12
Name: rank, dtype: int64

In [162]:
from sklearn.ensemble import RandomForestClassifier

params={
    'max_features':2,
    'n_estimators':60,
    'class_weight':'balanced',
    'random_state':42
}

rf=RandomForestClassifier(**params)
rf.fit(X_train,y_train)
y_pred_train=rf.predict_proba(X_train)[:,1]
y_pred=rf.predict_proba(X_test)[:,1]


print(rf.score(X_train,y_train),rf.score(X_test,y_test))

0.9887005649717514 0.8450704225352113

In [161]:
y_pred

array([0.5 , 0.25, 0.15, 0.4 , 0.2 , 0.1 , 0.1 , 0.05, 0.15, 0.15, 0.25,
       0.15, 0.25, 0.1 , 0.15, 0.  , 0.2 , 0.05, 0.25, 0.25, 0.  , 0.05,
       0.1 , 0.1 , 0.15, 0.  , 0.2 , 0.25, 0.  , 0.1 , 0.15, 0.25, 0.  ,
       0.1 , 0.3 , 0.  , 0.05, 0.25, 0.05, 0.15, 0.15, 0.1 , 0.  , 0.1 ,
       0.05, 0.  , 0.  , 0.6 , 0.  , 0.2 , 0.1 , 0.1 , 0.25, 0.05, 0.35,
       0.05, 0.1 , 0.15, 0.1 , 0.15, 0.1 , 0.3 , 0.05, 0.1 , 0.4 , 0.5 ,
       0.15, 0.2 , 0.2 , 0.  , 0.25])

In [83]:
#各特徴量の重要度の確認している
predictor.feature_importances_

array([0.06173823, 0.10551642, 0.01398076, 0.25182385, 0.11614648,
       0.        , 0.08991817, 0.09174605, 0.0761559 , 0.18793249,
       0.00504165, 0.        ])

In [49]:
X_train=X
y_train=y

GridSearchCVを用いて適切なハイパーパラメータを設定

In [67]:
import sklearn
from sklearn.ensemble import RandomForestClassifier
parameters = {"n_estimators":[i for i in range(10,100,10)],"criterion":["gini","entropy"],"max_depth":[i for i in range(1,6,1)] \
                    , 'min_samples_split': [2, 4, 10,12,16], "random_state":[3],}
rf=sklearn.model_selection.GridSearchCV(RandomForestClassifier(),param_grid=parameters,cv=5,n_jobs=5)
rf.fit(X_train,y_train)
predictor=rf.best_estimator_
print(predictor.score(X_train,y_train))

0.8870967741935484

In [66]:

X_train

,枠番,馬番,斤量,単勝,人気,年齢,体重,体重変化,着順_3R,賞金,性_牝,性_牡
200605020611,3,6,57,8.7,3,3,488,0,2.666667,1344.966667,0,1
200605020611,1,2,57,25.9,9,3,476,-6,6.333333,742.133333,0,1
200605020611,7,15,55,14.8,6,3,472,8,3.666667,740.733333,0,1
200605020611,2,4,57,15.9,7,3,436,-6,6.333333,270.000000,0,1
200605020611,8,17,57,43.2,11,3,486,0,3.666667,435.766667,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,1,1,57,87.0,13,3,488,0,8.000000,943.466667,0,1
201905020611,7,15,57,19.9,5,3,458,-4,3.000000,735.733333,0,1
201905020611,2,4,55,77.9,11,3,450,-2,2.000000,1890.566667,1,0
201905020611,5,9,57,285.2,17,3,474,4,8.666667,0.000000,0,1
201905020611,6,11,57,402.7,18,3,470,-4,4.333333,372.966667,0,1

In [81]:
y_pred1=predictor.predict(X_test)
y_pred=predictor.predict_proba(X_test)[:,1]
print(y_pred)

[0.04449934 0.54166667 0.59166667 0.00591033 0.16887019 0.06887019
 0.02       0.06887019 0.24968347 0.29818296 0.11703573 0.1815625
 0.29818296 0.44761608 0.12295017 0.13587631 0.825      0.18279221]

In [203]:
y_pred1=predictor.predict(X_test)

In [207]:
y_pred

array([0.12466923, 0.53815605, 0.12609188, 0.27954238, 0.29498856,
       0.08086627, 0.15241015, 0.15774331, 0.46621448, 0.16746636,
       0.09633704, 0.22104845, 0.12958714, 0.18552368, 0.1193976 ,
       0.31063348, 0.16243764, 0.1356115 , 0.2303942 , 0.14793584,
       0.11782025, 0.14113487, 0.1691977 , 0.07284981, 0.12794687])

In [206]:
y_test

201805020611    0
201805020611    0
201805020611    0
201805020611    0
201805020611    0
201805020611    0
201805020611    0
201805020611    0
201905020611    1
201905020611    1
201905020611    1
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
201905020611    0
Name: rank, dtype: int64

In [8]:
results2=pd.read_pickle('results2.pickle')

In [9]:
results2

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,horse_id,jockey_id,性,年齢,体重,体重変化
200605020611,1,3,6,ロジック,57,武豊,8.7,3,2003100454,00666,牡,3,488,0
200605020611,2,1,2,ファイングレイン,57,横山典弘,25.9,9,2003102667,00660,牡,3,476,-6
200605020611,3,7,15,キンシャサノキセキ,55,安藤勝己,14.8,6,2003110212,00945,牡,3,472,8
200605020611,4,2,4,アポロノサトリ,57,蛯名正義,15.9,7,2003110138,00663,牡,3,436,-6
200605020611,5,8,17,ドラゴンウェルズ,57,藤田伸二,43.2,11,2003110095,00705,牡,3,486,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201905020611,14,1,1,クリノガウディー,57,藤岡佑介,87.0,13,2016103690,01093,牡,3,488,0
201905020611,15,7,15,ヴィッテルスバッハ,57,戸崎圭太,19.9,5,2016104475,05386,牡,3,458,-4
201905020611,16,2,4,イベリス,55,浜中俊,77.9,11,2016101285,01115,牝,3,450,-2
201905020611,17,5,9,ミッキーブラック,57,岩田康誠,285.2,17,2016104626,05203,牡,3,474,4
201905020611,18,6,11,ロードグラディオ,57,大野拓弥,402.7,18,2016101154,01096,牡,3,470,-4

In [52]:
real_test_df=pd.read_html('https://race.netkeiba.com/race/shutuba.html?race_id=202005020611&rf=race_submenu')[0]
real_test_df.columns=['枠番','馬番','印','馬名','性齢','斤量','騎手','馬体重(増減)','単勝','人気','登録','めも','s']
real_test_df.drop(['印','登録','めも','s'],axis=1,inplace=True)

In [53]:
real_test_df

    枠番  馬番         馬名  性齢    斤量     騎手 馬体重(増減)       単勝     人気
0    1   1        シャチ  牡3  57.0    木幡育   美浦小桧山   456(0)  ---.-
1    1   2   タイセイビジョン  牡3  57.0    石橋脩    栗東西村  468(-6)  ---.-
2    2   3    レシステンシア  牝3  55.0   ルメール    栗東松下  476(-6)  ---.-
3    2   4   プリンスリターン  牡3  57.0    原田和    栗東加用   450(0)  ---.-
4    3   5  シャインガーネット  牝3  55.0     田辺    美浦栗田  464(+4)  ---.-
5    3   6   ギルデッドミラー  牝3  55.0     福永   栗東松永幹   468(0)  ---.-
6    4   7   メイショウチタン  牡3  57.0    吉田豊    栗東本田  454(-2)  ---.-
7    4   8    サクセッション  牡3  57.0    横山典    美浦国枝  514(+4)  ---.-
8    5   9     ラインベック  牡3  57.0     津村    栗東友道  468(-8)  ---.-
9    5  10  ハーモニーマゼラン  牡3  57.0     大野     美浦牧  510(-6)  ---.-
10   6  11     ラウダシオン  牡3  57.0  Ｍデムーロ   栗東斉藤崇   494(0)  ---.-
11   6  12   ボンオムトゥック  牝3  55.0    田中勝   栗東高橋亮   450(0)  ---.-
12   7  13    ニシノストーム  牡3  57.0    江田照    美浦杉浦  486(-6)  ---.-
13   7  14  ルフトシュトローム  牡3  57.0    レーン     美浦堀   482(0)  ---.-
14   7  15    ソウルトレイン  牡3  57.0    藤井勘    栗東西村  462(-2)  ---.-
15   8  16    ストーンリッジ  牡3  57.0     松田   栗東藤原英   456(0)  ---.-
16   8  17  サトノインプレッサ  牡3  57.0     武豊    栗東矢作  482(-6)  ---.-
17   8  18  ウイングレイテスト  牡3  57.0    横山武    美浦青木  486(-4)  ---.-

In [55]:
odds_list=[132.5,5.6,3.4,28.5,17.2,18.0,200.5,11.9,34.8,88.4,33.2,51.0,177.2,5.7,112.2,71.8,4.9,22.1]
popularity_list=[16,3,1,9,6,7,18,5,11,14,10,12,17,4,15,13,2,8]
real_test_df['人気']=popularity_list
real_test_df['単勝']=odds_list
real_test_df['性']=real_test_df['性齢'].map(lambda x:str(x)[0])
real_test_df['年齢']=real_test_df['性齢'].map(lambda x:str(x)[1:]).astype(int)
real_test_df .drop(['性齢'],axis=1,inplace=True)

In [57]:
real_test_df

    枠番  馬番         馬名    斤量     騎手 馬体重(増減)     単勝  人気  性  年齢
0    1   1        シャチ  57.0    木幡育   美浦小桧山  132.5  16  牡   3
1    1   2   タイセイビジョン  57.0    石橋脩    栗東西村    5.6   3  牡   3
2    2   3    レシステンシア  55.0   ルメール    栗東松下    3.4   1  牝   3
3    2   4   プリンスリターン  57.0    原田和    栗東加用   28.5   9  牡   3
4    3   5  シャインガーネット  55.0     田辺    美浦栗田   17.2   6  牝   3
5    3   6   ギルデッドミラー  55.0     福永   栗東松永幹   18.0   7  牝   3
6    4   7   メイショウチタン  57.0    吉田豊    栗東本田  200.5  18  牡   3
7    4   8    サクセッション  57.0    横山典    美浦国枝   11.9   5  牡   3
8    5   9     ラインベック  57.0     津村    栗東友道   34.8  11  牡   3
9    5  10  ハーモニーマゼラン  57.0     大野     美浦牧   88.4  14  牡   3
10   6  11     ラウダシオン  57.0  Ｍデムーロ   栗東斉藤崇   33.2  10  牡   3
11   6  12   ボンオムトゥック  55.0    田中勝   栗東高橋亮   51.0  12  牝   3
12   7  13    ニシノストーム  57.0    江田照    美浦杉浦  177.2  17  牡   3
13   7  14  ルフトシュトローム  57.0    レーン     美浦堀    5.7   4  牡   3
14   7  15    ソウルトレイン  57.0    藤井勘    栗東西村  112.2  15  牡   3
15   8  16    ストーンリッジ  57.0     松田   栗東藤原英   71.8  13  牡   3
16   8  17  サトノインプレッサ  57.0     武豊    栗東矢作    4.9   2  牡   3
17   8  18  ウイングレイテスト  57.0    横山武    美浦青木   22.1   8  牡   3

In [60]:

horse_weight_list=[456,468,476,450,464,468,454,514,468,510,494,450,486,482,462,456,482,486]
weight_chage_list=[0,-6,-6,0,+4,0,-2,+4,-8,-6,0,0,-6,0,-2,0,-6,-4]
real_test_df['体重']=horse_weight_list
real_test_df['体重変化']=weight_chage_list
real_test_df.drop(['馬体重(増減)'],axis=1,inplace=True)

In [68]:
real_test_df.drop(['騎手'],axis=1,inplace=True)

In [69]:
real_test_df

    枠番  馬番         馬名    斤量     単勝  人気  性  年齢   体重  体重変化
0    1   1        シャチ  57.0  132.5  16  牡   3  456     0
1    1   2   タイセイビジョン  57.0    5.6   3  牡   3  468    -6
2    2   3    レシステンシア  55.0    3.4   1  牝   3  476    -6
3    2   4   プリンスリターン  57.0   28.5   9  牡   3  450     0
4    3   5  シャインガーネット  55.0   17.2   6  牝   3  464     4
5    3   6   ギルデッドミラー  55.0   18.0   7  牝   3  468     0
6    4   7   メイショウチタン  57.0  200.5  18  牡   3  454    -2
7    4   8    サクセッション  57.0   11.9   5  牡   3  514     4
8    5   9     ラインベック  57.0   34.8  11  牡   3  468    -8
9    5  10  ハーモニーマゼラン  57.0   88.4  14  牡   3  510    -6
10   6  11     ラウダシオン  57.0   33.2  10  牡   3  494     0
11   6  12   ボンオムトゥック  55.0   51.0  12  牝   3  450     0
12   7  13    ニシノストーム  57.0  177.2  17  牡   3  486    -6
13   7  14  ルフトシュトローム  57.0    5.7   4  牡   3  482     0
14   7  15    ソウルトレイン  57.0  112.2  15  牡   3  462    -2
15   8  16    ストーンリッジ  57.0   71.8  13  牡   3  456     0
16   8  17  サトノインプレッサ  57.0    4.9   2  牡   3  482    -6
17   8  18  ウイングレイテスト  57.0   22.1   8  牡   3  486    -4

In [73]:
real_test_df['賞金']=[413.3,3504.3,4300,1050,1500,900,250,1200,550,500,1200,660,500,2300,660,700,1600,420]
real_test_df['着順_3R']=[4.5,1.3,2,3.3,2,1.66,7,3.3,7,3.3,3.5,2,4.3,1,2.6,3,1,6]

In [75]:
real_test_df.drop(['馬名'],axis=1,inplace=True)

In [76]:
X_test=pd.get_dummies(real_test_df)

In [77]:
X_test

    枠番  馬番    斤量     単勝  人気  年齢   体重  体重変化      賞金  着順_3R  性_牝  性_牡
0    1   1  57.0  132.5  16   3  456     0   413.3   4.50    0    1
1    1   2  57.0    5.6   3   3  468    -6  3504.3   1.30    0    1
2    2   3  55.0    3.4   1   3  476    -6  4300.0   2.00    1    0
3    2   4  57.0   28.5   9   3  450     0  1050.0   3.30    0    1
4    3   5  55.0   17.2   6   3  464     4  1500.0   2.00    1    0
5    3   6  55.0   18.0   7   3  468     0   900.0   1.66    1    0
6    4   7  57.0  200.5  18   3  454    -2   250.0   7.00    0    1
7    4   8  57.0   11.9   5   3  514     4  1200.0   3.30    0    1
8    5   9  57.0   34.8  11   3  468    -8   550.0   7.00    0    1
9    5  10  57.0   88.4  14   3  510    -6   500.0   3.30    0    1
10   6  11  57.0   33.2  10   3  494     0  1200.0   3.50    0    1
11   6  12  55.0   51.0  12   3  450     0   660.0   2.00    1    0
12   7  13  57.0  177.2  17   3  486    -6   500.0   4.30    0    1
13   7  14  57.0    5.7   4   3  482     0  2300.0   1.00    0    1
14   7  15  57.0  112.2  15   3  462    -2   660.0   2.60    0    1
15   8  16  57.0   71.8  13   3  456     0   700.0   3.00    0    1
16   8  17  57.0    4.9   2   3  482    -6  1600.0   1.00    0    1
17   8  18  57.0   22.1   8   3  486    -4   420.0   6.00    0    1